### ISSUE TITLE
🚀[FEA]: Add optional `dev` dependency to install packages needed for development

### ISSUE THREAD

**Issue by akshaysubr** [NVIDIA/modulus#124]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Medium

### Please provide a clear description of problem you would like to solve.

Currently, there isn't any easy way to figure out what packages are needed for a development setup. Eg: black, pre-commit, coverage, interrogate, etc. need to be installed to be able to run local checks but this isn't easy to figure out.

The best solution would be to create an [optional dependency](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies) in the `pyproject.toml` for a `dev` setup so you can install the package and dev dependencies while developing using
```bash
pip install -e .[dev]
```

### Describe any alternatives you have considered

Can document these dependencies in the contribution guide, but it isn't as seamless to use and actually install those packages.

**Comment by ktangsali** [comment]
This was added in this PR: https://github.com/NVIDIA/modulus/pull/150. Closing.
