### ISSUE TITLE
🐛[BUG]: Better handle the Tarball extracts

### ISSUE THREAD

**Issue by ktangsali** [NVIDIA/modulus#127]
### Version

main

### On which installation method(s) does this occur?

Source

### Describe the issue

Unsafe use of `tar.extractall()` [here](https://github.com/NVIDIA/modulus/blob/main/modulus/models/module.py#L262). For more details please see: https://bandit.readthedocs.io/en/1.7.5/plugins/b202_tarfile_unsafe_members.html

**Comment by NickGeneva** [comment]
Merged in https://github.com/NVIDIA/modulus/pull/161
