### ISSUE TITLE
🐛[BUG]: SFNO Preprocessor is missing utilities

### ISSUE THREAD

**Issue by dallasfoster** [NVIDIA/modulus#155]
### Version

0.2.1

### On which installation method(s) does this occur?

Docker, Pip, Source

### Describe the issue

The current implementation of the SFNO preprocessor is missing utilities to load orography and land sea mask. The [preprocessor.py](https://github.com/NVIDIA/modulus/blob/main/modulus/models/sfno/preprocessor.py) file imports a `utils.conditioning_utils.py` file that does not exist in order to load orograph and land/sea mask.

Ultimately, we need to add the following functions to the preprocessor file:
```python
import xarray as xr

def get_orography(orography_path):
    """ Returns the surface geopotential for each grid point
    after normalizing it to be in the unit range.
    """
    with xr.open_dataset(orography_path) as f:
        o = f.Z[0].data
        o = (o - o.min()) / (o.max() - o.min())
    return o

def get_land_mask(land_mask_path):
    """ Returns the land/sea mask for each grid point.
    """
    with xr.open_dataset(land_mask_path) as f:
        lsm = f.LSM[0].data
    return lsm 
```

Or, better yet, remove the preprocessor file and move it to `modulus-launch.py`.

**Comment by NickGeneva** [comment]
SFNO no longer in Modulus. Closing
