### ISSUE TITLE
🚀[FEA]: De-duplicate distributed utils between AFNO and SFNO

### ISSUE THREAD

**Issue by akshaysubr** [NVIDIA/modulus#173]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Medium

### Please provide a clear description of problem you would like to solve.

AFNO and SFNO share a lot of distributed utilities. Currently, these are duplicated. Would be good to consolidate both versions into a single version. See https://github.com/NVIDIA/modulus/pull/104#discussion_r1296538230

**Comment by NickGeneva** [comment]
Closing since SFNO is no longer in Modulus and distributed utils have been added to Makani
