### ISSUE TITLE
🚀[FEA]: Have better instructions for installing from source

### ISSUE THREAD

**Issue by ktangsali** [NVIDIA/modulus#176]
### Is this a new feature, an improvement, or a change to existing functionality?

Improvement

### How would you describe the priority of this feature request

Medium

### Please provide a clear description of problem you would like to solve.

The Modulus build currently require a lot of dependencies that are not currently fully supported via pip. The alternative to this is a Dockerfile, but this does not help the users who cannot use Docker due to other restrictions. While the Modulus pip experienece is being continuously improved, it would be good to have a robust source build instructions that mimic the same behavior as docker if built from source. This can include adding the dependencies unsupported via pip etc. as a submodule in the thirdparty folder (similar to a few other projects like https://github.com/pytorch/pytorch/tree/main/third_party )

**Comment by NickGeneva** [comment]
Docs and also readme have additional details now, so I think this can be closed
