### ISSUE TITLE
🚀[FEA]: Handle the CI stages better

### ISSUE THREAD

**Issue by ktangsali** [NVIDIA/modulus#190]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Low (would be nice)

### Please provide a clear description of problem you would like to solve.

Currently the CI stages description is becoming slightly ambiguous as we continue to add more stages to the existing ones. This can be revisited and cleaned-up to as the stages continue to evolve. This would require a few changes to the internal CI repos.

**Comment by NickGeneva** [comment]
Closing for now. No one has had troubles with the CI stages recently.
