### ISSUE TITLE
🚀[FEA]: Modulus Launch and Core integration

### ISSUE THREAD

**Issue by ktangsali** [NVIDIA/modulus#191]
### Is this a new feature, an improvement, or a change to existing functionality?

Change

### How would you describe the priority of this feature request

Medium

### Please provide a clear description of problem you would like to solve.

This is a proposal to bring the utilities from Modulus Launch into Modulus core and deprecate a separate pip wheel and dockerfile for the Modulus-Launch repo. The utilites in Modulus launch have matured enough to be widely applicable across different data-driven examples and can be integrated into the core Modulus package. The additional dependencies of Modulus Launch will be handled via the route of optional dependencies, i.e. with a `[launch]` option in the `.toml` file. From a user standpoint, the APIs/import statements are not affected as namespace packaging is adopted across the Modulus repos.

**Comment by NickGeneva** [comment]
Done in linked PR. Closing
