### ISSUE TITLE
[Question]: Not able to import Modulus sym classes

### ISSUE THREAD

**Issue by YouqiongLiu** [NVIDIA/modulus#289]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Critical (currently preventing usage)

### Please provide a clear description of problem you would like to solve.

installed the latest version of Modulus is using PyPi.
But, unable to add classes that a common docker installation can implement, as follow
from modulus.continuous.constraints.constraint import (
    PointwiseBoundaryConstraint,
    PointwiseInteriorConstraint,
    IntegralBoundaryConstraint,
    PointwiseConstraint,
)

What if I want to do this in nvidia-modulus 0.4.0?

**Comment by NickGeneva** [comment]
Hi @YouqiongLiu 

Did you install Modulus symbolic using:

```bash
pip install nvidia-modulus.sym
```

**Comment by YouqiongLiu** [comment]
Thx @NickGeneva 
I have installed nvidia-modulus: 0.4.0 and the latest version of nvidia-modulus.sym is using PyPi.
But, the following programs cannot be run . Error importing pysdf. Make sure 'libsdf.so' is in LD_LIBRARY_PATH and pysdf is installed.
How can I solve this problem?

import modulus.sym
from modulus.sym.geometry.tessellation import Tessellation

**Comment by NickGeneva** [comment]
Hi @YouqiongLiu 

PySDF is only available inside the Modulus docker container. Not the python package. We recommend using the docker container if you wish to use this feature.

**Comment by ChenQian9104** [comment]
I am using the docker container (latest image version 24.12) but still got the error: 

from modulus.sym.geometry.tessellation import Tessellation
ModuleNotFoundError: No module named 'modulus.sym' 

is it possible to make the modulus.sym available not only in the docker container? We want to benchmark our model on XAeroNet.
