### ISSUE TITLE
GraphCast loss function different from original DeepMind version

### ISSUE THREAD

**Issue by cr-metdev** [NVIDIA/modulus#301]
I noticed that the graphcast loss function in this repository differs from what was used in the [original graphcast paper](https://arxiv.org/abs/2212.12794), since the implemented here does not weight loss based on pressure level or type of variable. Just wondering if there was a reason for this or if there are plans to implement the level/variable weighting in the graphcast loss function in future updates?

**Comment by mnabian** [comment]
Hi @cr-metdev , thanks for posting your question. We started with a simplified version of the loss function, but now in a recent PR, the implementation has improved to include other loss weightings based on pressure level or type of variable: https://github.com/NVIDIA/modulus/pull/554

**Comment by mnabian** [comment]
Closing as complete
