### ISSUE TITLE
🚀[FEA]: Adding Physics-Informed Nonlinear Shallow Water Equations example.

### ISSUE THREAD

**Issue by fresleven** [NVIDIA/modulus#339]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Low (would be nice)

### Please provide a clear description of problem you would like to solve.

I have created an example for a Physics-Informed Nonlinear Shallow Water Equations example.

https://github.com/NVIDIA/modulus/pull/338

**Comment by mnabian** [comment]
Merged: https://github.com/NVIDIA/modulus/commit/cdedc86e325f42e7c02c988eb90125c054010fbd
