### ISSUE TITLE
🚀[FEA]: Save "model card" from unified recipe that is usable by E2mip

### ISSUE THREAD

**Issue by loliverhennigh** [NVIDIA/modulus#343]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature, Adding model card to unified recipe that will allow transferring the model and all needed meta data over for inference services and validation. 

### How would you describe the priority of this feature request

Critical

**Comment by ram-cherukuri** [comment]
@loliverhennigh Is there an epic this task is associated with?
