### ISSUE TITLE
[Enhancement] Add Inference Script to CorrDiff Example

### ISSUE THREAD

**Issue by dallasfoster** [NVIDIA/modulus#384]
It would be beneficial to have a simplified script in the CorrDiff example that shows how to run inference on a single netcdf/zarr/xarray array. This inference script would be minimal but would have necessary IO to be run as CLI. It might also be beneficial to automatically download data from ARCO ERA5 for users.

**Comment by dallasfoster** [comment]
The availability of a checkpoint is a concern.

**Comment by mnabian** [comment]
@dallasfoster could you please provide an update on this issue?
Now we have CorrDiff NIM, CorrDiff inference package on NGC, and CorrDiff-Mini inference in Modulus. Are these sufficient for your purpose?

**Comment by dallasfoster** [comment]
I think the main solution to this has come from the CorrDiff NIM, which is NVAIE, but also through Earth2Studio, which has an example of the type of [minimal inference script](https://nvidia.github.io/earth2studio/examples/04_corrdiff_inference.html#sphx-glr-examples-04-corrdiff-inference-py) that I described.

I will mark this as closed.
