### ISSUE TITLE
🚀[FEA]: VFGN improvements

### ISSUE THREAD

**Issue by mnabian** [NVIDIA/modulus#404]
### Is this a new feature, an improvement, or a change to existing functionality?

Improvement

### How would you describe the priority of this feature request

Critical (currently preventing usage)

### Please provide a clear description of problem you would like to solve.

The VFGN model contributed by HP Labs requires some improvements, including:

- Using Hydra for config handling
- Moving the large files to NGC resources
- Fixing the linting requirements for the README
- Enabling GPU inference (optional)
- Dependency management for the pytests
- Update the changelog [DONE]
- Uncomment model examples

**Comment by dearleiii** [comment]
Solved

- [x] Using Hydra for config handling
- [x] Moving the large files to NGC resources
- [ ] Fixing the linting requirements for the README
- [ ] Enabling GPU inference (optional)
- [ ] Dependency management for the pytests
- [ ] Update the changelog [DONE]
- [ ] Uncomment model examples
