### ISSUE TITLE
[BUG] [CorrDiff]: The deterministic sampler scales the conditional input

### ISSUE THREAD

**Issue by nbren12** [NVIDIA/modulus#418]
I think there is a similar bug to #229 in the sampler:

https://github.com/NVIDIA/modulus/blob/9b0b7cc71fb280c028e09ee56726c0caa387c63b/modulus/utils/generative/sampler.py#L188

x_lr should not be scaled by "s". It is not part of the evolved diffusion process, it is a conditional input.

**Comment by nbren12** [comment]
cc @mnabian

**Comment by mnabian** [comment]
Yair made a PR here to fix this: https://github.com/NVIDIA/modulus/pull/373
There were some issues reported by Tao, and we ended up reverting this PR here: https://github.com/NVIDIA/modulus/pull/396

**Comment by nbren12** [comment]
@mnabian this is a separate issue that only effects inference.

BTW, I also had a PR on the conditional scaling: https://github.com/NVIDIA/modulus/pull/381
