### ISSUE TITLE
NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for Rfft(1) node with name '/Rfft'

### ISSUE THREAD

**Issue by Atharva7K** [NVIDIA/modulus#42]
I have a model that uses `torch.fft.rfft` and `torch.fft.irfft`, since ONNX does not support these I want to use `modulus.models.layers.fft.rfft` and `modulus.models.layers.irfft` as an replacement. When I try to run the below sample code:

```py
import modulus.models.layers.fft as fft
import torch
import onnxruntime

class Customrfft(torch.nn.Module):
    def forward(self, y):
        return fft.rfft(y, dim=-1)

t = torch.randn((1, 8, 64, 96))
model = Customrfft()

torch.onnx.export(model, t, 'test.onnx')
ort_session = onnxruntime.InferenceSession("test.onnx")
ort_outputs = ort_session.run(t)

```

I get error:

```py
NotImplemented                            Traceback (most recent call last)

<ipython-input-5-8d37e437a72c> in <cell line: 4>()
      2 
      3 # Load the model
----> 4 ort_session = onnxruntime.InferenceSession("test.onnx")
      5 ort_outputs = ort_session.run(t)

1 frames

/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py in _create_inference_session(self, providers, provider_options, disabled_optimizers)
    433 
    434         # initialize the C++ InferenceSession
--> 435         sess.initialize_session(providers, provider_options, disabled_optimizers)
    436 
    437         self._sess = sess

NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for Rfft(1) node with name '/Rfft'
```

Can someone please assist me on how I can implement the two functions so that I can convert my model to ONNX and use it. Thanks

**Comment by NickGeneva** [comment]
Hi @Atharva7K 

Yes, ONNX fft support has caused some trouble for us in the past. I see you're likely following an example from the [unit tests](https://github.com/NVIDIA/modulus/blob/main/test/deploy/test_onnx_fft.py#L96). Can you see if creating the ONNX session using the built in Modulus utilities works?

Namely:
```
model = Customrfft()

onnx_model = export_to_onnx_stream(model, x)
output_ort = run_onnx_inference(onnx_model, (x,))
```

I know RFFT is only supported on GPUs, so you need to make sure you're using CUDA provider in your ONNX session. The Modulus util has a note on [this](https://github.com/NVIDIA/modulus/blob/main/modulus/deploy/onnx/utils.py#L105).

**Comment by Atharva7K** [comment]
Thanks for the response @NickGeneva . I tried with the code you mentioned:

```py
class Customrfft(torch.nn.Module):
    def forward(self, y):
        return fft.rfft(y, dim=-1)

t = torch.randn((1, 8, 64, 96), device='cuda')
model = Customrfft()
model.to('cuda')

onnx_model = export_to_onnx_stream(model, t)
output_ort = run_onnx_inference(onnx_model, (t,))
```

I get the exact same error. 

Additionally, I would also like to use `modulus.models.layers.irfft` but in the tests there's a message saying "Must install custom ORT 1.14.0. Other versions do not work \
        due to bug in IRFFT: https://github.com/microsoft/onnxruntime/issues/13236". Can you kindly guide on how to install custom ORT? Will simply doing `pip install onnxruntime==1.14.0` work?

**Comment by NickGeneva** [comment]
The version check is in the unit tests for a custom build of onnx which we use in our container but do not distribute. It had a slight bug fix but I think newer version of onnx have this fix (not tested).

For a pip install you need to install both ONNX runtime and runtime gpu since RFFT is only supported on GPUs.
I ran an interactive session of [Nvidia PyTorch docker ](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/tags) `nvcr.io/nvidia/pytorch:22.12-py3` and ran the following installs and ONNX ran fine.

```
pip install --upgrade pip
pip install nvidia-modulus
pip install onnxruntime
pip install onnxruntime-gpu
```

ONNX is viewed as an optional dependency for us.

**Comment by Atharva7K** [comment]
Thanks a lot @NickGeneva , rfft is working now. Apparently I wasn't using `onnxruntime-gpu`. I still have to try out irfft, once I get it to work I will close the issue

**Comment by NickGeneva** [comment]
Closing since scope of original issue has been resolved. Re-open if needed.

**Comment by Atharva7K** [comment]
Hello @NickGeneva , I am trying to implement alternative to `torch.fft.irfft` as I mentioned earlier:

```py
class RFFT(torch.nn.Module):
    def forward(self, y):
        return fft.rfft(y, dim=-1)

t = torch.randn((1, 8, 64, 96), device='cuda')

model_rfft = RFFT()
model_rfft.to('cuda')

onnx_model_rfft = export_to_onnx_stream(model_rfft, t)
output_ort_rfft = run_onnx_inference(onnx_model_rfft, (t,))


class IRFFT(torch.nn.Module):
    def forward(self, y):
        return fft.irfft(y, n=96, dim=-1)
model_irfft = IRFFT()
model_irfft.to('cuda')

onnx_model_irfft = export_to_onnx_stream(model_irfft, output_ort_rfft[0])
output_ort_irfft = run_onnx_inference(onnx_model_irfft, output_ort_rfft[0],)
```

But I get following error:

```py
---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

[<ipython-input-7-d658582c24d5>](https://localhost:8080/#) in <cell line: 7>()
      5 model_irfft.to('cuda')
      6 
----> 7 onnx_model_irfft = export_to_onnx_stream(model_irfft, output_ort_rfft[0])
      8 output_ort_irfft = run_onnx_inference(onnx_model_irfft, output_ort_rfft[0],)

15 frames

[/usr/local/lib/python3.10/dist-packages/modulus/models/layers/fft.py](https://localhost:8080/#) in _check_padding_irfft(sizes, dim, inp_sizes)
    379         expected_size = 2 * (inp_sizes[dim[-1]] - 1)
    380         if s != expected_size:
--> 381             raise RuntimeError(
    382                 f"Padding/trimming is not yet supported, got sizes {sizes}"
    383                 f", DFT dims {dim}, input dims {inp_sizes}"

RuntimeError: Padding/trimming is not yet supported, got sizes (96,), DFT dims (-1,), input dims torch.Size([1, 8, 64, 49, 2]), expected last size 2.
```

Can you please assist regarding how to resolve this. Thanks!

For some context, the whole point of all this is that I am trying to convert [Autoformer](https://github.com/thuml/Autoformer) to ONNX, but their [autocorrelation](https://github.com/thuml/Autoformer/blob/e6371e24f2ae2dd53e472edefdd5814c5176f864/layers/AutoCorrelation.py#L118) operations use PyTorch's FFT functions which are not supported by ONNX.

**Comment by delldu** [comment]
@NickGeneva ,  you told us "RFFT is only supported on GPUs",  We should how to if want using RFFT on CPU ? Many thanks

**Comment by NickGeneva** [comment]
Hi @delldu 

This is in the context of running ONNX rffts, unless ORT has been updated to support rffts on cpu operations then its limited to GPUs. You should consult ORT docs regarding this. Thanks.
