### ISSUE TITLE
🚀[FEA]: augmentation added for corrdiff training

### ISSUE THREAD

**Issue by MortezaMardani** [NVIDIA/modulus#421]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Critical (currently preventing usage)

### Please provide a clear description of problem you would like to solve.

currently the augmentation has been deactivated in the modulus codebase for training. it would be very useful to add it. the lag is augment, that refers to augmentation probability. if augment=0, no augmentation.

**Comment by mnabian** [comment]
Merged https://github.com/NVIDIA/modulus/pull/426
