### ISSUE TITLE
Provide the Vortex Shedding dataset on NGC for the GNN+Transformer example 

### ISSUE THREAD

**Issue by mnabian** [NVIDIA/modulus#433]
### Is this a new feature, an improvement, or a change to existing functionality?

Improvement

### How would you describe the priority of this feature request

Medium

**Comment by mnabian** [comment]
@ktangsali this asset is ready. Could you please publish publicly? Thanks
@ram-cherukuri for viz

**Comment by ktangsali** [comment]
@mnabian can we fix this? 

![image](https://github.com/NVIDIA/modulus/assets/71059996/25499e96-af70-4df9-856b-27e92176f680)

**Comment by mnabian** [comment]
@ktangsali fixed, thanks

**Comment by ktangsali** [comment]
This was published https://catalog.ngc.nvidia.com/orgs/nvidia/teams/modulus/resources/modulus_datasets_cylinder-flow
