### ISSUE TITLE
📚[DOC]: No SFNO in models

### ISSUE THREAD

**Issue by osl202** [NVIDIA/modulus#521]
Hi,

I was wondering where the sfnonet.py file is in the modulus repository please?  I can see it provided here but not in the main branch: https://github.com/NVIDIA/modulus/blob/b8e27c5c4ebc409e53adaba9832138743ede2785/modulus/models/sfno/sfnonet.py

**Comment by ktangsali** [comment]
SFNO is provided in Modulus using the entry point mechanism. To use SFNO, you will have to install modulus using `pip install nvidia-modulus[makani]`. To refer the usage of the model, please check a minimal example [here](https://github.com/NVIDIA/modulus/blob/main/test/models/test_sfno.py), or the full recipe [here](https://github.com/NVIDIA/modulus/tree/main/examples/weather/unified_recipe#sfno-training).
