### ISSUE TITLE
📚[DOC]: Link missing to contact the NVIDIA team to request dataset.

### ISSUE THREAD

**Issue by AnnaVitali** [NVIDIA/modulus#532]
### How would you describe the priority of this documentation request

Medium

### Is this for new documentation, or an update to existing docs?

Update

### Describe the incorrect/future/missing documentation

In the example at this location: _examples/cfd/ahmed_body_mgn_ when clicking to "[NVIDIA Modulus team](https://github.com/NVIDIA/modulus/blob/main/examples/cfd/ahmed_body_mgn/modulus-team@nvidia.com)" , 404 error is launched.

**Comment by mnabian** [comment]
This has been fixed here: https://github.com/NVIDIA/modulus/pull/595
