### ISSUE TITLE
🐛[BUG]: Too many open files error in ahmed_body_mgn example

### ISSUE THREAD

**Issue by naruhikot** [NVIDIA/modulus#551]
### Version

24.04

### On which installation method(s) does this occur?

Docker

### Describe the issue

Converted docker container to apptainer. When I ran training script, I got "too many open files" error. See the trimmed log bellow. 

### Minimum reproducible example

```shell
apptainer run --nv --bind `pwd`,$USER_DIR $CONTAINER_IMAGE bash -c "python train.py"
```

### Relevant log output

```shell
...
OSError: [Errno 24] Too many open files: '/usr/local/lib/python3.10/dist-packages/pandas/core/api.py'
OSError: [Errno 24] Too many open files: '/usr/local/lib/python3.10/dist-packages/pandas/core/algorithms.py'
OSError: [Errno 24] Too many open files: '/usr/local/lib/python3.10/dist-packages/pandas/core/config_init.py'
...
```

### Environment details

```shell
Environment location: TSUBAME4.0 (https://www.t4.gsic.titech.ac.jp/en)
ulimit -n is set to 16384 on this system
```

**Comment by Alexey-Kamenev** [comment]
Please try the most recent version of Modulus, as I remember, there was previously an issue with visualizers not releasing the resources.

Also, recommend to set max number of open files to a larger number (Docker has default of `1048576`) .
