### ISSUE TITLE
🚀[FEA]: Add transolver model.

### ISSUE THREAD

**Issue by luohk19** [NVIDIA/modulus#592]
### Is this a new feature, an improvement, or a change to existing functionality?

Improvement

### How would you describe the priority of this feature request

Medium

### Please provide a clear description of problem you would like to solve.

Add transolver model from ICML2024 in solving PDEs.
https://github.com/NVIDIA/modulus/pull/591

**Comment by mnabian** [comment]
Merged: https://github.com/NVIDIA/modulus/pull/591
