### ISSUE TITLE
Make nvfuser optional

### ISSUE THREAD

**Issue by loliverhennigh** [NVIDIA/modulus#60]
The base wheel of pytorch does not have nvfusor and will not work for local installs. I highly recommend making this optional and have a fallback if users aren't using nvfusor.

https://github.com/NVIDIA/modulus/blob/bad7e00e21915c155d232bfea67dc985f7fa9045/modulus/models/layers/fused_silu.py#L18

**Comment by oddcard2** [comment]
Up
