### ISSUE TITLE
📚[DOC]: CorrDiff: The URL of the Zarr dataset is invalid

### ISSUE THREAD

**Issue by CYC23** [NVIDIA/modulus#624]
### How would you describe the priority of this documentation request

Medium

### Is this for new documentation, or an update to existing docs?

Update

### Describe the incorrect/future/missing documentation

In the last of [modulus/examples/generative
/corrdiff/README.md](https://github.com/NVIDIA/modulus/tree/main/examples/generative/corrdiff) of Dataset part, the URL for the data set provided in the article is no longer valid:https://catalog.ngc.nvidia.com/orgs/nvidia/teams/modulus/resources/cwa_dataset.

**Comment by mnabian** [comment]
Hi @CYC23 , we fixed the link and updated the README.
https://github.com/NVIDIA/modulus/issues/431

**Comment by CYC23** [comment]
Hi @mnabian, I have received the new link, thank you.
