### ISSUE TITLE
🐛[BUG]: datapipes.healpix is not importable

### ISSUE THREAD

**Issue by yairchn** [NVIDIA/modulus#680]
### Version

0.7.0

### On which installation method(s) does this occur?

Pip

### Describe the issue

Both `modulus/datapipes/__init__.py` and `modulus/datapipes/healpix/__init__.py` seem to be empty which does not allow to install  `datapipes/healpix`.
This blocks the use of projects like NVDLESM of this datapipes for training. 

### Minimum reproducible example

pip install modulus 
$ python 
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import modulus 
>>> modulus.datapipes.healpix
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'modulus.datapipes' has no attribute 'healpix'
>>>

**Comment by dallasfoster** [comment]
Closed with #681
