### ISSUE TITLE
Question about the CorrDiff Example

### ISSUE THREAD

**Issue by MyGitHub-G** [NVIDIA/modulus#704]
when i run `python train.py`, the error:
```
Error executing job with overrides: []
Traceback (most recent call last):
  File "/public/home/shizhm2050/gexl/modulus/examples/generative/corrdiff/train.py", line 104, in main
    img_out_channels = len(dataset.output_channels())
  File "/public/home/shizhm2050/gexl/modulus/examples/generative/corrdiff/datasets/cwb.py", line 448, in output_channels
    return [out_channels[i] for i in self.out_channels]
  File "/public/home/shizhm2050/gexl/modulus/examples/generative/corrdiff/datasets/cwb.py", line 448, in <listcomp>
    return [out_channels[i] for i in self.out_channels]
IndexError: list index out of range
```
what is the reason?

and

cwb_train.yaml文件中in_channels: [0, 1, 2, 3, 4, 9, 10, 11, 12, 17, 18, 19]是什么意思，为什么不是0~19，代表20个变量呢

**Comment by MyGitHub-G** [comment]
cwb.py  ZarrDataset class:
```
def input_channels(self):
        """Metadata for the input channels. A list of dictionaries, one for each channel"""
        in_channels = self._dataset.input_channels()
        # print(in_channels)  # 20个输入变量
        # print(self.in_channels) # [0, 1, 2, 3, 4, 9, 10, 11, 12, 17, 18, 19]
        in_channels = [in_channels[i] for i in self.in_channels]
        return in_channels

    def output_channels(self):
        """Metadata for the output channels. A list of dictionaries, one for each channel"""
        out_channels = self._dataset.output_channels()
        print(out_channels) 
        # [ChannelMetadata(name='maximum_radar_reflectivity', level='', auxiliary=False), 
        #   ChannelMetadata(name='temperature_2m', level='', auxiliary=False), 
        #   ChannelMetadata(name='eastward_wind_10m', level='', auxiliary=False), 
        #   ChannelMetadata(name='northward_wind_10m', level='', auxiliary=False)]
        # print(self.out_channels) #[0, 17, 18, 19]
        # return [out_channels[i] for i in self.out_channels]
        return [out_channels[i] for i in range(len(self.out_channels))]
```
in the output_channels function, the self.out_channels is [0, 17, 18, 19], not [0,1,2,3]
17 results the IndexError
i changed the` return [out_channels[i] for i in self.out_channels] `to` return [out_channels[i] for i in range(len(self.out_channels))]`
is it a bug?

**Comment by MyGitHub-G** [comment]
cwb.py  ZarrDataset class:
```
def input_channels(self):
        """Metadata for the input channels. A list of dictionaries, one for each channel"""
        in_channels = self._dataset.input_channels()
        # print(in_channels)  # 20个输入变量
        # print(self.in_channels) # [0, 1, 2, 3, 4, 9, 10, 11, 12, 17, 18, 19]
        in_channels = [in_channels[i] for i in self.in_channels]
        return in_channels

    def output_channels(self):
        """Metadata for the output channels. A list of dictionaries, one for each channel"""
        out_channels = self._dataset.output_channels()
        print(out_channels) 
        # [ChannelMetadata(name='maximum_radar_reflectivity', level='', auxiliary=False), 
        #   ChannelMetadata(name='temperature_2m', level='', auxiliary=False), 
        #   ChannelMetadata(name='eastward_wind_10m', level='', auxiliary=False), 
        #   ChannelMetadata(name='northward_wind_10m', level='', auxiliary=False)]
        # print(self.out_channels) #[0, 17, 18, 19]
        # return [out_channels[i] for i in self.out_channels]
        return [out_channels[i] for i in range(len(self.out_channels))]
```
in the output_channels function, the self.out_channels is [0, 17, 18, 19], not [0,1,2,3]
17 results the IndexError
i changed the` return [out_channels[i] for i in self.out_channels] `to` return [out_channels[i] for i in range(len(self.out_channels))]`
is it a bug?

**Comment by MyGitHub-G** [comment]
cwb.py ZarrDataset class __getitem__ function:
```
# channels
        input = input[self.in_channels, :, :]
        # target = target[self.out_channels, :, :]
        target = target[range(len(self.out_channels)), :, :]
```
`target = target[self.out_channels, :, :]` results error `IndexError: index 17 is out of bounds for axis 0 with size 4`
changed to `target = target[range(len(self.out_channels)), :, :]`
is it a bug?

**Comment by zomosky** [comment]
> cwb.py ZarrDataset class **getitem** function:
> 
> ```
> # channels
>         input = input[self.in_channels, :, :]
>         # target = target[self.out_channels, :, :]
>         target = target[range(len(self.out_channels)), :, :]
> ```
> 
> `target = target[self.out_channels, :, :]` results error `IndexError: index 17 is out of bounds for axis 0 with size 4` changed to `target = target[range(len(self.out_channels)), :, :]` is it a bug?

I have changed it in the **conf/yaml** by cfg.dataset.out_channels = [0, 1, 2, 3], also the channels means **the channels choice in the zarr**, you can see channels by zarr.tree() 

我也觉得这是一个bug，也有可能是之前的训练集的结构不一样导致的，可以直接在yaml或者运行的时候改变channel就行，因为作为output的输出的数据集size为4，所以可以设置为**cfg.dataset.out_channels = [0, 1, 2, 3]** 可以通过简单的zarr库和zarr.tree()方法查看zarr数据库的结构
```python
import zarr as zr
zrpath = '/home/cwa_dataset/cwa_dataset.zarr'
ze = zr.open(zrpath, mode = 'r')
zr.load(zrpath)
group = zr.open_consolidated(zrpath)
ze = zr.open(zrpath, mode = 'r')
zr.tree(ze)
```

**Comment by MyGitHub-G** [comment]
> > cwb.py ZarrDataset class **getitem** function:
> > ```
> > # channels
> >         input = input[self.in_channels, :, :]
> >         # target = target[self.out_channels, :, :]
> >         target = target[range(len(self.out_channels)), :, :]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `target = target[self.out_channels, :, :]` results error `IndexError: index 17 is out of bounds for axis 0 with size 4` changed to `target = target[range(len(self.out_channels)), :, :]` is it a bug?
> 
> I have changed it in the **conf/yaml** by cfg.dataset.out_channels = [0, 1, 2, 3], also the channels means **the channels choice in the zarr**, you can see channels by zarr.tree()
> 
> 我也觉得这是一个bug，也有可能是之前的训练集的结构不一样导致的，可以直接在yaml或者运行的时候改变channel就行，因为作为output的输出的数据集size为4，所以可以设置为**cfg.dataset.out_channels = [0, 1, 2, 3]** 可以通过简单的zarr库和zarr.tree()方法查看zarr数据库的结构
> 
> import zarr as zr
> zrpath = '/home/cwa_dataset/cwa_dataset.zarr'
> ze = zr.open(zrpath, mode = 'r')
> zr.load(zrpath)
> group = zr.open_consolidated(zrpath)
> ze = zr.open(zrpath, mode = 'r')
> zr.tree(ze)
