### ISSUE TITLE
🚀[FEA]: BF16 support in static capture

### ISSUE THREAD

**Issue by mnabian** [NVIDIA/modulus#75]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Medium

### Please provide a clear description of problem you would like to solve.

BF16 is used in GraphCast and needs to be supported in the static capture.

**Comment by NickGeneva** [comment]
bfloat16 should be fine in static capture both when using AMP or without (graphcast is entirely bfloat16). Closing.
