### ISSUE TITLE
🚀[FEA]: Update SFNO to use `DistributedManager` without model parallelism

### ISSUE THREAD

**Issue by akshaysubr** [NVIDIA/modulus#79]
### Is this a new feature, an improvement, or a change to existing functionality?

Improvement

### How would you describe the priority of this feature request

Critical (currently preventing usage)

### Please provide a clear description of problem you would like to solve.

SFNO currently uses a separate `comm_v2` module for distributed setup. This should be changed so it can use the `DistributedManager` like all other models and utils in Modulus

**Comment by NickGeneva** [comment]
I believe this was updated in Makani, closing
