### ISSUE TITLE
🐛[BUG]: Fix datapipe unit tests to not error on failure for local testing

### ISSUE THREAD

**Issue by NickGeneva** [NVIDIA/modulus#88]
### Version

0.1.0

### On which installation method(s) does this occur?

Source

### Describe the issue

Pytest for datapipe currently errors because one does not have access to test datasets locally most of the time.

Unit tests should skip / xfail if the data CI fodler is not there.

They should error if this folder is present and the test fails.

**Comment by ktangsali** [comment]
This was fixed in this PR: https://github.com/NVIDIA/modulus/pull/150
