### ISSUE TITLE
🐛[BUG]: Error with using modulus docker image as base image in dockerfile

### ISSUE THREAD

**Issue by ankurmahesh** [NVIDIA/modulus#93]
### Version

23.05 (docker)

### On which installation method(s) does this occur?

Docker

### Describe the issue

I am trying to use the docker image (nvcr.io/nvidia/modulus/modulus:23.05) as a starting point in a Dockerfile: I'd like to add some of my own packages on top.  However, I get the error reported below when I try to use it as a starting point.  The first line in the Dockerfile (FROM nvcr.io/nvidia/modulus/modulus:23.05) causes the issue.

From googling it appears that there can be many reasons for getting the error message I get (e.g. a problem with [NGC](https://github.com/triton-inference-server/server/issues/3805) or [not logging in](https://forums.developer.nvidia.com/t/sdk-v0-2-docker-build-errors-in-using-a-development-container/218679).  When I try to use a different NVIDIA base image, (e.g. FROM nvcr.io/nvidia/pytorch:$PYT_VER-py3 as env), then everything works smoothly.  

If you have any guidance on how to avoid this error, that would be much appreciated.

### Minimum reproducible example

```shell
FROM nvcr.io/nvidia/modulus/modulus:23.05
```

### Relevant log output

```shell
=> ERROR [internal] load metadata for nvcr.io/nvidia/modulus/modulus:23.05                                                                                                     0.4s

failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to authorize: rpc error: code = Unknown desc = failed to fetch anonymous token: unexpected status: 401 Unauthorized
```

### Environment details

```shell
I get the error when I run

docker build  -t amahesh19/modulus_base:0.1 .

in the directory with the Dockerfile.
```

**Comment by ankurmahesh** [comment]
Hi Nick, Thanks so much for looking into this. 

I am able to successfully pull this image.  Moreover, I tried rerunning the exact same line with the exact same Dockerfile:

`docker build  -t amahesh19/modulus_base:0.1 .`

and it worked this time!  The docker image now gets built successfully.  'm not exactly sure what changed.  I apologize for the trouble associated with making this issue: I guess everything appears resolved now.  Thanks so much for looking into this for me.  I appreciate your help.

**Comment by NickGeneva** [comment]
No worries, @ankurmahesh . Docker sometimes has a mind of its own... I'll close this issue for now, but do not hesitate to re-open / open a new one if you have some additional trouble.
